name: project-two-dl
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - jupyter
  - pip
  - pip:
      - tensorflow>=2.13
      # For Apple Silicon:
      # - tensorflow-macos
      # - tensorflow-metal
      # If you prefer PyTorch instead:
      # - torch
      # - torchvision
